name: agitation
baseurl: /agitation
description: A Control Structure for Cancellation
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.1+95-160fb855-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
