name: agitation
baseurl: /agitation
description: A Control Structure for Cancellation
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.2.0-M1+6-12d6f81d-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
