name: agitation
baseurl: /agitation
description: A Control Structure for Cancellation
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.2.0-M1+10-3c10d2f4-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
